//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18033
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBCSApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IBCSApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developed by Víctor Mora.
        /// </summary>
        public static string AboutPageDeveloper {
            get {
                return ResourceManager.GetString("AboutPageDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Follow on Twitter.
        /// </summary>
        public static string AboutPageFollow {
            get {
                return ResourceManager.GetString("AboutPageFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy policy.
        /// </summary>
        public static string AboutPagePrivacy {
            get {
                return ResourceManager.GetString("AboutPagePrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://pkg.apphb.com/privacy.
        /// </summary>
        public static string AboutPagePrivacyUrl {
            get {
                return ResourceManager.GetString("AboutPagePrivacyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you have any idea on how to improve this app? Maybe new features we could add? Found a bug or an issue? Do not hesitate and get in touch through our Twitter account so we can all together create a better app!.
        /// </summary>
        public static string AboutPageSupportBody {
            get {
                return ResourceManager.GetString("AboutPageSupportBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Support.
        /// </summary>
        public static string AboutPageSupportTitle {
            get {
                return ResourceManager.GetString("AboutPageSupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ViVictorMora.
        /// </summary>
        public static string AboutPageTwitter {
            get {
                return ResourceManager.GetString("AboutPageTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.0.0.0.
        /// </summary>
        public static string AboutPageVersion {
            get {
                return ResourceManager.GetString("AboutPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pkg.apphb.com.
        /// </summary>
        public static string AboutPageWeb {
            get {
                return ResourceManager.GetString("AboutPageWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a clear log.
        /// </summary>
        public static string AppBarClearLog {
            get {
                return ResourceManager.GetString("AppBarClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string AppBarHome {
            get {
                return ResourceManager.GetString("AppBarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a instructions.
        /// </summary>
        public static string AppBarInstructions {
            get {
                return ResourceManager.GetString("AppBarInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a logout.
        /// </summary>
        public static string AppBarLogout {
            get {
                return ResourceManager.GetString("AppBarLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nfc Secure Notes.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BLUETOOTH.
        /// </summary>
        public static string BluetoothActivateCaption {
            get {
                return ResourceManager.GetString("BluetoothActivateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bluetooth is turned off. Change settings now?.
        /// </summary>
        public static string BluetoothActivateMessage {
            get {
                return ResourceManager.GetString("BluetoothActivateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string CreateAccountCreate {
            get {
                return ResourceManager.GetString("CreateAccountCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will shortly recieve an email to activate your account..
        /// </summary>
        public static string CreateAccountCreatedMessage {
            get {
                return ResourceManager.GetString("CreateAccountCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks for signing up!.
        /// </summary>
        public static string CreateAccountCreatedTitle {
            get {
                return ResourceManager.GetString("CreateAccountCreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hey, we need both a name and email in order to create your account..
        /// </summary>
        public static string CreateAccountDataError {
            get {
                return ResourceManager.GetString("CreateAccountDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a email.
        /// </summary>
        public static string CreateAccountEmail {
            get {
                return ResourceManager.GetString("CreateAccountEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name.
        /// </summary>
        public static string CreateAccountName {
            get {
                return ResourceManager.GetString("CreateAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a create account.
        /// </summary>
        public static string CreateAccountPageTitle {
            get {
                return ResourceManager.GetString("CreateAccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a password.
        /// </summary>
        public static string CreateAccountPassword {
            get {
                return ResourceManager.GetString("CreateAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a password confirmation.
        /// </summary>
        public static string CreateAccountPasswordConfirmation {
            get {
                return ResourceManager.GetString("CreateAccountPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! It seems like your passwords do not match..
        /// </summary>
        public static string CreateAccountPasswordError {
            get {
                return ResourceManager.GetString("CreateAccountPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I have read and agree to the .
        /// </summary>
        public static string CreateAccountServiceConditions {
            get {
                return ResourceManager.GetString("CreateAccountServiceConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need to accept the terms of service..
        /// </summary>
        public static string CreateAccountServiceConditionsError {
            get {
                return ResourceManager.GetString("CreateAccountServiceConditionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a terms of service.
        /// </summary>
        public static string CreateAccountServiceConditionsLink {
            get {
                return ResourceManager.GetString("CreateAccountServiceConditionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://pkg.apphb.com/conditions.
        /// </summary>
        public static string CreateAccountServiceConditionsUrl {
            get {
                return ResourceManager.GetString("CreateAccountServiceConditionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a decrypting secure note.
        /// </summary>
        public static string DecryptingMessage {
            get {
                return ResourceManager.GetString("DecryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string DecryptMessageMessage {
            get {
                return ResourceManager.GetString("DecryptMessageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! It seems like this message was not intended for you..
        /// </summary>
        public static string DecryptMessageMessageError {
            get {
                return ResourceManager.GetString("DecryptMessageMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a decrypt message.
        /// </summary>
        public static string DecryptMessagePageTitle {
            get {
                return ResourceManager.GetString("DecryptMessagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recipient.
        /// </summary>
        public static string DecryptMessageRecipient {
            get {
                return ResourceManager.GetString("DecryptMessageRecipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a encrypting message.
        /// </summary>
        public static string EncryptingLink {
            get {
                return ResourceManager.GetString("EncryptingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a encrypting secure note.
        /// </summary>
        public static string EncryptingMessage {
            get {
                return ResourceManager.GetString("EncryptingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sharing.
        /// </summary>
        public static string InstructionsPageEmailAndSocial {
            get {
                return ResourceManager.GetString("InstructionsPageEmailAndSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identity Based Encryption is a public cryptographic scheme in which any piece of text can act as a valid public key (e.g email addresses, phone numbers, domain names, dates or a combination of both). Our server, generates the corresponding private keys provided users validate their identities correctly..
        /// </summary>
        public static string InstructionsPageIbeP1 {
            get {
                return ResourceManager.GetString("InstructionsPageIbeP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forget about key management, certificates and all that stuff. If you want to send a secure message to a friend, you just need to provide their email and the app will take care of the rest. Pretty cool, huh?.
        /// </summary>
        public static string InstructionsPageIbeP2 {
            get {
                return ResourceManager.GetString("InstructionsPageIbeP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ibe.
        /// </summary>
        public static string InstructionsPageIbeTitle {
            get {
                return ResourceManager.GetString("InstructionsPageIbeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Near Field Communication (NFC) technology makes life easier and more convenient for consumers around the world by making it simpler to make transactions, exchange digital content, and connect electronic devices with a touch..
        /// </summary>
        public static string InstructionsPageNfcP1 {
            get {
                return ResourceManager.GetString("InstructionsPageNfcP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To use NFC, make sure that &apos;Tap+Send&apos; is activated in your phone settings..
        /// </summary>
        public static string InstructionsPageNfcP2 {
            get {
                return ResourceManager.GetString("InstructionsPageNfcP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nfc.
        /// </summary>
        public static string InstructionsPageNfcTitle {
            get {
                return ResourceManager.GetString("InstructionsPageNfcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To analyze a NFC tag content simply tap it and move to the log page..
        /// </summary>
        public static string InstructionsPageReadingP1 {
            get {
                return ResourceManager.GetString("InstructionsPageReadingP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the tag contains a standarized message (NDEF) then its size and content type will be shown..
        /// </summary>
        public static string InstructionsPageReadingP2 {
            get {
                return ResourceManager.GetString("InstructionsPageReadingP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note: the Windows Phone 8 operating system does not support parsing propietary or protected tags such as passports or credit cards..
        /// </summary>
        public static string InstructionsPageReadingP3 {
            get {
                return ResourceManager.GetString("InstructionsPageReadingP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a reading tags.
        /// </summary>
        public static string InstructionsPageReadingTags {
            get {
                return ResourceManager.GetString("InstructionsPageReadingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a secure notes.
        /// </summary>
        public static string InstructionsPageSecureNotes {
            get {
                return ResourceManager.GetString("InstructionsPageSecureNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In order to create a secure note, move to the secure notes page, fill in the title and the content of the note and press encrypt. Whenever a NFC tag or device is close to your phone you will be able to write or send the note..
        /// </summary>
        public static string InstructionsPageSecureNotesP1 {
            get {
                return ResourceManager.GetString("InstructionsPageSecureNotesP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note: if the NFC tag in which you&apos;re trying to write your note has a small size you should check the &apos;Shorten Url&apos; option to reduce the final size of the message..
        /// </summary>
        public static string InstructionsPageSecureNotesP2 {
            get {
                return ResourceManager.GetString("InstructionsPageSecureNotesP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Besides writing secure notes you can also send secure messages to your contacts by email or by sharing it in social networks..
        /// </summary>
        public static string InstructionsPageSharingP1 {
            get {
                return ResourceManager.GetString("InstructionsPageSharingP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To do so, simply move to the email or social page, fill the form in and send the message..
        /// </summary>
        public static string InstructionsPageSharingP2 {
            get {
                return ResourceManager.GetString("InstructionsPageSharingP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note: this version of the app only allows users to have one identity, their registration email. More identities will be supported soon!.
        /// </summary>
        public static string InstructionsPageSharingP3 {
            get {
                return ResourceManager.GetString("InstructionsPageSharingP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nfc Secure Notes will let you store secure notes in NFC tags or send them to other devices. You can also send secure messages to your contacts by email or through social networks..
        /// </summary>
        public static string InstructionsPageWelcomeP1 {
            get {
                return ResourceManager.GetString("InstructionsPageWelcomeP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One of the key features of this app is the use of Identity Based Cryptosystems to protect messages..
        /// </summary>
        public static string InstructionsPageWelcomeP2 {
            get {
                return ResourceManager.GetString("InstructionsPageWelcomeP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Just write a message, encrypt it and tap&amp;hold a tag to write the note in it. You can also tap a tag containing a secure note and the app will decrypt it for you..
        /// </summary>
        public static string InstructionsPageWelcomeP3 {
            get {
                return ResourceManager.GetString("InstructionsPageWelcomeP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is also a tag analyzer which will show you the size and content type of the tags you tap..
        /// </summary>
        public static string InstructionsPageWelcomeP4 {
            get {
                return ResourceManager.GetString("InstructionsPageWelcomeP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a welcome.
        /// </summary>
        public static string InstructionsPageWelcomeTitle {
            get {
                return ResourceManager.GetString("InstructionsPageWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message intented to.
        /// </summary>
        public static string LinkMessage {
            get {
                return ResourceManager.GetString("LinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IBCS encrypted message.
        /// </summary>
        public static string LinkTitle {
            get {
                return ResourceManager.GetString("LinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a email.
        /// </summary>
        public static string LoginPageEmail {
            get {
                return ResourceManager.GetString("LoginPageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check that your email and password are correct.
        /// </summary>
        public static string LoginPageErrorMessage {
            get {
                return ResourceManager.GetString("LoginPageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn&apos;t log you in..
        /// </summary>
        public static string LoginPageErrorTitle {
            get {
                return ResourceManager.GetString("LoginPageErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sign in.
        /// </summary>
        public static string LoginPageLoginButton {
            get {
                return ResourceManager.GetString("LoginPageLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a password.
        /// </summary>
        public static string LoginPagePassword {
            get {
                return ResourceManager.GetString("LoginPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a sign up.
        /// </summary>
        public static string LoginPageSignUpButton {
            get {
                return ResourceManager.GetString("LoginPageSignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a login.
        /// </summary>
        public static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a send to device.
        /// </summary>
        public static string MainPageComposerDeviceButton {
            get {
                return ResourceManager.GetString("MainPageComposerDeviceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a encrypt.
        /// </summary>
        public static string MainPageComposerEncyptButton {
            get {
                return ResourceManager.GetString("MainPageComposerEncyptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tag composer.
        /// </summary>
        public static string MainPageComposerHeader {
            get {
                return ResourceManager.GetString("MainPageComposerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string MainPageComposerMessage {
            get {
                return ResourceManager.GetString("MainPageComposerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shorten url.
        /// </summary>
        public static string MainPageComposerShortenUrl {
            get {
                return ResourceManager.GetString("MainPageComposerShortenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a write to tag.
        /// </summary>
        public static string MainPageComposerTagButton {
            get {
                return ResourceManager.GetString("MainPageComposerTagButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string MainPageComposerTitle {
            get {
                return ResourceManager.GetString("MainPageComposerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a encrypting message.
        /// </summary>
        public static string MainPageMailEncrypting {
            get {
                return ResourceManager.GetString("MainPageMailEncrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mail.
        /// </summary>
        public static string MainPageMailHeader {
            get {
                return ResourceManager.GetString("MainPageMailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string MainPageMailMessage {
            get {
                return ResourceManager.GetString("MainPageMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This message is ciphered using an Identity Based Cryptosystem. In order the decrypt it download the Windows Phone IBCS app!.
        /// </summary>
        public static string MainPageMailMessageAd {
            get {
                return ResourceManager.GetString("MainPageMailMessageAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This is the end of the message. By clicking this link from your phone, the app will automatically decrypt it..
        /// </summary>
        public static string MainPageMailMessageEnd {
            get {
                return ResourceManager.GetString("MainPageMailMessageEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string MainPageMailSend {
            get {
                return ResourceManager.GetString("MainPageMailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject.
        /// </summary>
        public static string MainPageMailSubject {
            get {
                return ResourceManager.GetString("MainPageMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To.
        /// </summary>
        public static string MainPageMailTo {
            get {
                return ResourceManager.GetString("MainPageMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a log.
        /// </summary>
        public static string MainPageNfcLogHeader {
            get {
                return ResourceManager.GetString("MainPageNfcLogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tap NFC tags or devices to analyze them.
        /// </summary>
        public static string MainPageNfcLogTitle {
            get {
                return ResourceManager.GetString("MainPageNfcLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a social.
        /// </summary>
        public static string MainPageSocialHeader {
            get {
                return ResourceManager.GetString("MainPageSocialHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identity.
        /// </summary>
        public static string MainPageSocialIdentity {
            get {
                return ResourceManager.GetString("MainPageSocialIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string MainPageSocialMessage {
            get {
                return ResourceManager.GetString("MainPageSocialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share.
        /// </summary>
        public static string MainPageSocialSendButton {
            get {
                return ResourceManager.GetString("MainPageSocialSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Package name.
        /// </summary>
        public static string NdefAAR {
            get {
                return ResourceManager.GetString("NdefAAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a App Id.
        /// </summary>
        public static string NdefLaunchAppRecordId {
            get {
                return ResourceManager.GetString("NdefLaunchAppRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Platform.
        /// </summary>
        public static string NdefLaunchAppRecordPlatform {
            get {
                return ResourceManager.GetString("NdefLaunchAppRecordPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record type.
        /// </summary>
        public static string NdefMessageRecordType {
            get {
                return ResourceManager.GetString("NdefMessageRecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MIME type.
        /// </summary>
        public static string NdefRecordMimeType {
            get {
                return ResourceManager.GetString("NdefRecordMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        public static string NdefSpAction {
            get {
                return ResourceManager.GetString("NdefSpAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string NdefSpTitle {
            get {
                return ResourceManager.GetString("NdefSpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titles.
        /// </summary>
        public static string NdefSpTitles {
            get {
                return ResourceManager.GetString("NdefSpTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URI.
        /// </summary>
        public static string NdefSpUri {
            get {
                return ResourceManager.GetString("NdefSpUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language code.
        /// </summary>
        public static string NdefTextRecordLanguage {
            get {
                return ResourceManager.GetString("NdefTextRecordLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text.
        /// </summary>
        public static string NdefTextRecordText {
            get {
                return ResourceManager.GetString("NdefTextRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NDEF, unknown format.
        /// </summary>
        public static string NdefUnknown {
            get {
                return ResourceManager.GetString("NdefUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, we are having problems reaching the server. Try again later.
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t write to tag.
        /// </summary>
        public static string NfcMessageTooLong {
            get {
                return ResourceManager.GetString("NfcMessageTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message written.
        /// </summary>
        public static string NfcMessageWritten {
            get {
                return ResourceManager.GetString("NfcMessageWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Writeable tag size:.
        /// </summary>
        public static string NfcWriteableTagSize {
            get {
                return ResourceManager.GetString("NfcWriteableTagSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oops! Your device does not support NFC.
        /// </summary>
        public static string NoNfcError {
            get {
                return ResourceManager.GetString("NoNfcError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device / tag arrived.
        /// </summary>
        public static string NotifyDeviceArrived {
            get {
                return ResourceManager.GetString("NotifyDeviceArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Device / tag departed.
        /// </summary>
        public static string NotifyDeviceDeparted {
            get {
                return ResourceManager.GetString("NotifyDeviceDeparted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://twitter.com/vivictormora.
        /// </summary>
        public static string TwitterUrl {
            get {
                return ResourceManager.GetString("TwitterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://pkg.apphb.com.
        /// </summary>
        public static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
    }
}
